//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppStats.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using AppStats.Models;
    
    
    public partial class AppStatsContext : DbContext
    {
        public AppStatsContext()
            : base("name=AppStatsContext")
        {
            Database.SetInitializer<AppStatsContext>(null);

            if (!Database.Exists())
            {
                throw new Exception("Database " + Database.Connection.ConnectionString + " does not exist.");
            }
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //modelBuilder.Conventions.Remove<System.Data.Entity.ModelConfiguration.Conventions.PluralizingTableNameConvention>();
        }
    
        public DbSet<DropFile> DropFiles { get; set; }
        public DbSet<DropFileStore> DropFileStores { get; set; }
        public DbSet<AppStats.Models.Environment> Environments { get; set; }
        public DbSet<Language> Languages { get; set; }
        public DbSet<Record> Records { get; set; }
        public DbSet<TimeType> TimeTypes { get; set; }
        public DbSet<TimeStatistic> TimeStatistics { get; set; }
    }
}
