//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppStats.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class AppStatsEntities1 : DbContext
    {
        public AppStatsEntities1()
            : base("name=AppStatsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DropFile> DropFiles { get; set; }
        public DbSet<DropFileStore> DropFileStores { get; set; }
        public DbSet<Environment> Environments { get; set; }
        public DbSet<Language> Languages { get; set; }
        public DbSet<Record> Records { get; set; }
        public DbSet<TimeType> TimeTypes { get; set; }
        public DbSet<TimeStatistic> TimeStatistics { get; set; }
    
        public virtual int GetRecords(Nullable<int> pc, Nullable<int> n, Nullable<int> lang, Nullable<int> environment)
        {
            var pcParameter = pc.HasValue ?
                new ObjectParameter("pc", pc) :
                new ObjectParameter("pc", typeof(int));
    
            var nParameter = n.HasValue ?
                new ObjectParameter("n", n) :
                new ObjectParameter("n", typeof(int));
    
            var langParameter = lang.HasValue ?
                new ObjectParameter("lang", lang) :
                new ObjectParameter("lang", typeof(int));
    
            var environmentParameter = environment.HasValue ?
                new ObjectParameter("environment", environment) :
                new ObjectParameter("environment", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetRecords", pcParameter, nParameter, langParameter, environmentParameter);
        }
    
        public virtual int UpdateStatistics()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateStatistics");
        }
    
        public virtual int UpdateStatistics1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateStatistics1");
        }
    }
}
