//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppStats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DropFile
    {
        public DropFile()
        {
            this.Records = new HashSet<Record>();
            this.DropFileStores = new HashSet<DropFileStore>();
        }
    
        public int DropFileId { get; set; }
        public string Filename { get; set; }
        public System.DateTime CraeteDtTm { get; set; }
        public bool IsActive { get; set; }
        public byte LanguageId { get; set; }
        public byte EnvironmentId { get; set; }
    
        public virtual Environment Environment { get; set; }
        public virtual Language Language { get; set; }
        public virtual ICollection<Record> Records { get; set; }
        public virtual ICollection<DropFileStore> DropFileStores { get; set; }
    }
}
