//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppStats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public Language()
        {
            this.DropFiles = new HashSet<DropFile>();
            this.Records = new HashSet<Record>();
        }
    
        public byte LanguageId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<DropFile> DropFiles { get; set; }
        public virtual ICollection<Record> Records { get; set; }
    }
}
