//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppStats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int RecordId { get; set; }
        public System.DateTime CreateDtTm { get; set; }
        public string CreateUser { get; set; }
        public int DropFileId { get; set; }
        public int Size { get; set; }
        public int ProcessorCount { get; set; }
        public System.DateTime ExecuteDtTm { get; set; }
        public decimal TimeValue { get; set; }
        public byte TimeTypeId { get; set; }
        public byte LanguageId { get; set; }
        public byte EnvironmentId { get; set; }
    
        public virtual DropFile DropFile { get; set; }
        public virtual Environment Environment { get; set; }
        public virtual Language Language { get; set; }
        public virtual TimeType TimeType { get; set; }
    }
}
