//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppStats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeStatistic
    {
        public int DatasetSize { get; set; }
        public int ProcessorCount { get; set; }
        public Int64 TimeTypeId { get; set; }
        public decimal Mean { get; set; }
        public decimal Median { get; set; }
        public decimal Average { get; set; }
        public decimal Q1Mean { get; set; }
        public decimal Q3Mean { get; set; }
        public decimal Mode { get; set; }
        public Int64 LanguageId { get; set; }
        public Int64 EnvironmentId { get; set; }
        public decimal Min { get; set; }
        public decimal Max { get; set; }
        public decimal MeanAverage { get; set; }
        public int RecordCount { get; set; }
        public Int64 TimeStatisticId { get; set; }
        public System.DateTime BatchTime { get; set; }
    }
}
